// src/lib/bot/siteRules.js
// ------------------------------------------------------- pointing around the site
// Each rule: words people use (English + Afrikaans mixed), where to send them.
export const SITE = [
  {
    id: "list-event",
    words: ["list my event", "add my event", "add an event", "post an event", "lys my gebeurtenis", "lys n gebeurtenis",
            "gebeurtenis lys", "gebeurtenis plaas", "plaas n gebeurtenis", "my event", "my funksie"],
    href: "/list-your-event",
    af: { text: "Het jy 'n gebeurtenis? Lys dit hier, dan sien almal dit.", label: "📅 Lys My Gebeurtenis" },
    en: { text: "Got an event? List it here and everyone can see it.", label: "📅 List My Event" },
  },
  {
    id: "list-business",
    words: ["list my business", "add my business", "register my business", "list business", "advertise my business",
            "lys my besigheid", "lys besigheid", "besigheid lys", "besigheid registreer", "besigheid byvoeg",
            "adverteer my besigheid", "my besigheid op die bulletin", "advertensie plaas", "besigheid advertensie",
            "advertensie vir my besigheid", "my besigheid adverteer", "adverteer besigheid"],
    href: "/list-your-business",
    af: { text: "Wil jy jou besigheid op die Bulletin hê? Lys dit hier — dis gratis.", label: "🏪 Lys My Besigheid" },
    en: { text: "Want your business on the Bulletin? List it here — it's free.", label: "🏪 List My Business" },
  },
  {
    id: "jobs",
    words: ["job", "jobs", "vacancy", "vacancies", "hiring", "employment", "looking for work", "looking for a job",
            "find work", "find a job", "need a job", "want a job", "want work", "get a job", "apply for",
            "vakature", "vakatures", "soek werk", "werk soek", "werkloos", "werksgeleentheid", "indiensneming",
            "werk beskikbaar", "post beskikbaar", "werk aanbied", "werk adverteer", "werkers", "werker",
            "personeel", "iemand aanstel", "aanstel", "pos adverteer", "offer work", "offer a job",
            "hire someone", "hire staff", "looking to hire", "advertise a job", "post a job"],
    only: ["werk", "work", "werke"],
    href: "/jobs",
    af: { text: "Soek jy werk, of wil jy werk adverteer? Dit is alles op die Werk-blad.", label: "💼 Gaan na Werk" },
    en: { text: "Looking for work, or want to advertise a job? It's all on the Jobs page.", label: "💼 Go to Jobs" },
  },
  {
    id: "sell",
    words: ["sell", "selling", "for sale", "classifieds", "classified", "second hand", "secondhand",
            "verkoop", "te koop", "koop en verkoop", "tweedehands", "tweede hands"],
    // "a shop that sells wool" is a business search, not someone selling something
    block: [/\bwat\b.*\b(verkoop|koop)\b/, /\bwinkel\b/, /\bshop\b/, /\bstore\b/, /\bwho sells\b/, /\bwaar\b.*\bkoop\b/],
    only: ["verkoop", "koop", "sell", "buy"],
    href: "/classifieds",
    af: { text: "Wil jy iets verkoop (of koop)? Plaas dit by Koop & Verkoop, dan sien die dorp dit.", label: "🛒 Koop & Verkoop" },
    en: { text: "Want to sell (or buy) something? Put it on Buy & Sell so the town can see it.", label: "🛒 Buy & Sell" },
  },
  {
    id: "emergency",
    words: ["emergency", "police", "ambulance", "fire department", "hospital", "urgent", "help me now",
            "nood", "noodgeval", "noodnommer", "noodnommers", "polisie", "brandweer", "ambulans", "hospitaal", "dringend"],
    href: "/emergency",
    af: { text: "Dis dringend? Hier is die belangrike nommers. As dit lewensgevaarlik is, bel dadelik die nooddienste.", label: "🚨 Nood Kontakte" },
    en: { text: "Urgent? Here are the important numbers. If it's life-threatening, call the emergency services right away.", label: "🚨 Emergency Contacts" },
  },
  {
    id: "events",
    words: ["events", "whats on", "what is happening", "whats happening", "happening this weekend", "this weekend",
            "gebeurtenisse", "gebeure", "wat gebeur", "wat is aan die gang", "wat se aan die gang", "hierdie naweek", "aktiwiteite"],
    href: "/",
    af: { text: "Kyk bo op die tuisblad onder \"Wat Gebeur\" — daar is al die gebeurtenisse.", label: "🔥 Wat Gebeur" },
    en: { text: "Check the \"What's Happening\" section on the home page — all the events are there.", label: "🔥 What's Happening" },
  },
  {
    id: "feed",
    words: ["lost", "found", "lost and found", "lost dog", "lost cat", "community", "feed", "announcement", "announcements",
            "birthday", "warning", "recommendation", "ask the town", "verlore", "gevind", "verlore en gevind", "vermis",
            "gemeenskap", "aankondiging", "aankondigings", "verjaarsdag", "waarskuwing", "aanbeveling", "dorpsnuus"],
    href: "/feed",
    af: { text: "Vir vrae, verlore-en-gevind, aankondigings en dorpsnuus is die Gemeenskap Feed die plek.", label: "💬 Gemeenskap Feed" },
    en: { text: "For questions, lost & found, announcements and town news, the Community Feed is the place.", label: "💬 Community Feed" },
  },
  {
    id: "games",
    words: ["game", "games", "play", "bored", "glitch cafe", "chess", "sudoku", "battleship", "snake", "checkers",
            "speletjie", "speletjies", "speel", "verveeld", "skaak"],
    href: "/games",
    af: { text: "Verveeld? 😄 Glitch Cafe het speletjies vir 'n bietjie plesier.", label: "🕹️ Glitch Cafe" },
    en: { text: "Bored? 😄 Glitch Cafe has games for a bit of fun.", label: "🕹️ Glitch Cafe" },
  },
  {
    id: "post-update",
    words: ["post an update", "submit an update", "post a special", "plaas n opdatering", "plaas n spesiaal", "opdatering plaas"],
    href: "/business-updates/submit",
    af: { text: "Wil jy 'n opdatering of spesiaal plaas? Hier is die vorm.", label: "📢 Plaas Opdatering" },
    en: { text: "Want to post an update or special? Here's the form.", label: "📢 Post an Update" },
  },
  {
    id: "specials",
    words: ["special", "specials", "deals", "promotions", "new stock", "business news", "business updates",
            "spesiaal", "spesiale", "aanbieding", "aanbiedinge", "nuwe voorraad", "besigheidsopdaterings", "besigheid nuus"],
    href: "/business-updates",
    af: { text: "Spesiale aanbiedinge, nuwe voorraad en nuus van plaaslike besighede is by Besigheidsopdaterings.", label: "📢 Besigheidsopdaterings" },
    en: { text: "Specials, new stock and news from local businesses are on Business Updates.", label: "📢 Business Updates" },
  },
  {
    id: "contact",
    words: ["contact", "contact you", "contact us", "who runs this", "who built this", "suggestion", "suggestions",
            "feedback", "report a problem", "complain", "complaint", "kontak", "kontak julle", "skakel julle",
            "voorstel", "voorstelle", "terugvoer", "kla", "klagte", "wie bestuur"],
    href: "/contact",
    af: { text: "Wil jy ons kontak, of het jy 'n idee of voorstel? Ons hoor graag van jou.", label: "✉️ Kontak Ons" },
    en: { text: "Want to get in touch, or have an idea or suggestion? We'd love to hear from you.", label: "✉️ Contact Us" },
  },
  {
    id: "about",
    words: ["what is this", "what is this site", "about", "about you", "about us", "mission",
            "wat is dit", "wat is hierdie", "oor ons", "oor julle", "missie"],
    href: "/mission",
    af: { text: "Ons Bulletin is 'n gratis plek waar elke plaaslike besigheid en gemeenskapsgeleentheid op een plek is.", label: "ℹ️ Ons Missie" },
    en: { text: "Ons Bulletin is a free place where every local business and community event is in one place.", label: "ℹ️ Our Mission" },
  },
  {
    id: "install",
    words: ["install", "download", "app", "add to home screen", "installeer", "laai af", "aflaai", "program"],
    href: "/",
    af: { text: "Jy kan die Bulletin soos 'n app op jou foon sit. Kyk vir die installeer-knoppie op die tuisblad.", label: "📲 Tuisblad" },
    en: { text: "You can put the Bulletin on your phone like an app. Look for the install button on the home page.", label: "📲 Home Page" },
  },
  {
    id: "privacy",
    words: ["privacy", "terms", "terms and conditions", "my data", "privaatheid", "terme", "voorwaardes", "my data"],
    href: "/privacy",
    af: { text: "Ons privaatheidsbeleid en terme is hier.", label: "🔒 Privaatheid" },
    en: { text: "Our privacy policy and terms are here.", label: "🔒 Privacy" },
    extra: { href: "/terms", af: "📄 Terme", en: "📄 Terms" },
  },
  {
    id: "directory",
    words: ["all businesses", "business list", "directory", "show me businesses", "alle besighede", "lys van besighede", "besigheidslys"],
    href: "/besighede",
    af: { text: "Hier is al ons plaaslike besighede.", label: "🏪 Ons Besighede" },
    en: { text: "Here are all our local businesses.", label: "🏪 Our Businesses" },
  },
];
